CREATE TABLE tickets
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mail_id        VARCHAR(255)                            NOT NULL,
    full_name      VARCHAR(255),
    email          VARCHAR(255)                            NOT NULL,
    phone          VARCHAR(50),
    company_name   VARCHAR(255),
    subject        VARCHAR(500),
    raw_email_text TEXT                                    NOT NULL,
    serial_numbers JSONB,
    device_type    VARCHAR(255),
    status         VARCHAR(30)                             NOT NULL,
    sentiment      VARCHAR(255),
    category       VARCHAR(255),
    response       TEXT,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    answered_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);